name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Set MyRunNumber
variables: 
  MyRunNumber: $(Date:yyyyMMdd)
  dateVar: $[format('{0:ddMMyyyy}', pipeline.startTime)] #format('{0:yyyyMMdd}', pipeline.startTime)


steps:
- script: |
    echo $(MyRunNumber) # display MyRunNumber
    echo $(dateVar)