name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Set MyRunNumber
variables: 
  MyRunNumber: $(Date:yyyyMMdd)


steps:
- script: echo $(MyRunNumber) # display MyRunNumber